# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DYNAMODB_TABLE_POSTS=${DYNAMODB_TABLE_POSTS}
      - DYNAMODB_TABLE_COMMENTS=${DYNAMODB_TABLE_COMMENTS}
      - PROCESSING_ENDPOINT=${PROCESSING_ENDPOINT}
      - MAX_RETRIES=${MAX_RETRIES}
    volumes:
      - .:/app