version: '3.8'

services:
  app:
    build: .
    container_name: poke-app
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      DLQ_QUEUE_URL: http://localstack:4566/000000000000/dead-letter-queue
      PROCESSING_ENDPOINT: http://httpbin.org/post
      CIRCUIT_BREAKER_THRESHOLD: 5
      CIRCUIT_BREAKER_RESET_TIMEOUT: 60

  redis:
    image: redis:6.2.13-alpine3.18
    container_name: poke-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    command: redis-server --save "" --appendonly no

  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    container_name: poke-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 3

  localstack:
    image: localstack/localstack:2.3.0
    container_name: poke-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - PERSISTENCE=1
      - LOCALSTACK_HOST=localstack
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  dynamodb_data:
  localstack_data: